apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: team-data
  labels:
    owner-team: data-team
    cape-policy/managed: "true"
spec:
  podSelector: {}
  policyTypes:
    - Ingress
